name: Update GitHub Stats

# Trigger the workflow
on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api/top-langs/?username=huzaifakarim1&layout=compact&theme=dark&count_private=true&include_all_commits=true&token=${{ secrets.GH_TOKEN }}"
